package com.grappim.kit.buildlogic

import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.compose.compiler.gradle.ComposeCompilerGradlePluginExtension
import java.io.File

// Opt-in Compose Compiler stability audit — see docs/compose/stability-reports.md in whichever
// app enables it. Off by default: -PcomposeStabilityReport to generate *-classes.txt /
// *-composables.txt.
//
// Deliberately does NOT set targetKotlinPlatforms to restrict which target gets reports: that
// property doesn't just filter report output, it's also what ComposeCompilerGradleSubplugin
// .isApplicable() uses to decide whether the Compose compiler plugin applies to a compilation at
// all. Restricting it to `jvm` would silently disable Compose's bytecode transformation for the
// Android target of every KMP UI module. Avoid duplicate per-target reports operationally
// instead (compile only one target's task when running the audit).
fun Project.configureComposeStabilityReports() {
    if (!project.hasProperty("composeStabilityReport")) return
    extensions.configure<ComposeCompilerGradlePluginExtension> {
        metricsDestination.set(layout.buildDirectory.dir("compose_reports"))
        reportsDestination.set(layout.buildDirectory.dir("compose_reports"))
    }
}

/**
 * Trust-lists foreign types the Compose compiler has no marker for but which are genuinely
 * immutable (all-`val`), so it stops defaulting them to Unstable. Unlike the reports above, this
 * changes real generated bytecode on every build, debug and release alike, so it is never gated
 * behind `-PcomposeStabilityReport`.
 *
 * wallosmobile/wayprint-only as of 2026-09-09 (SHARED_LIBRARY_PLAN.md's "build-logic" section) —
 * TaigaMobileNova hasn't adopted a `config/compose/stability_config.conf` file, so this stays
 * opt-in (`enabled = false` by default) rather than assuming every consuming app has that file.
 */
fun Project.configureComposeStabilityConfig(enabled: Boolean = false) {
    if (!enabled) return
    extensions.configure<ComposeCompilerGradlePluginExtension> {
        // `rootDir` wrapped through `layout.file(Provider<File>)`, not `rootProject.layout...` —
        // the latter reads another project's (":") mutable state, which Isolated Projects forbids.
        stabilityConfigurationFiles.add(
            layout.file(provider { File(rootDir, "config/compose/stability_config.conf") })
        )
    }
}
